# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x15\n\x07Request\x12\n\n\x02ID\x18\x01 \x01(\x05\"3\n\x08Response\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2%\n\x04User\x12\x1d\n\x04Info\x12\x08.Request\x1a\t.Response\"\x00\x42\x0bZ\tgrpc/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\tgrpc/user'
  _globals['_REQUEST']._serialized_start=14
  _globals['_REQUEST']._serialized_end=35
  _globals['_RESPONSE']._serialized_start=37
  _globals['_RESPONSE']._serialized_end=88
  _globals['_USER']._serialized_start=90
  _globals['_USER']._serialized_end=127
# @@protoc_insertion_point(module_scope)
